### ISSUE TITLE
Air quality not working

### ISSUE THREAD

**Issue by efouladi** [geometric-weather-foss/GeometricWeather#16]
![Screenshot_20210309-111342_Geometric_Weather](https://user-images.githubusercontent.com/1150145/110857138-c4116600-82b8-11eb-8900-bc14f2ae9395.png)

**Comment by mbestavros** [comment]
@efouladi Thanks for the bug report!

You would probably be better served by reporting this [upstream](https://github.com/WangDaYeeeeee/GeometricWeather), since this fork is only meant to implement a specific set of changes.

Thanks!

**Comment by efouladi** [comment]
Thanks. I tried the original app and it doesn't even show the option for air quality. It look like they removed it at some point
