### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by D3SOX** [geometric-weather-foss/GeometricWeather#17]
Sorry if I annoy you with this but there were no commits since Dec 28, 2020 and upstream is already on version `3.004`.
I just wanted to ask if you can merge the upstream changes?

**Comment by mbestavros** [comment]
@D3SOX Hey! There's actually been significant progress in upstreaming the patches applied in this fork upstream; you can see that [here](https://github.com/WangDaYeeeeee/GeometricWeather/pull/180).

Given that progress, I'm not intending to update this fork further, though it should still work until the fully FOSS version is available upstream and on F-Droid.

**Comment by D3SOX** [comment]
Thanks for this information. I did not know about that, I'll take a look and maybe compile it myself.
