### ISSUE TITLE
Functionless Announcement strip and Actual position 

### ISSUE THREAD

**Issue by Moostek** [geometric-weather-foss/GeometricWeather#18]
Hello there, i know there is a new (original) version of Geometric Weather from Wang, but i still prefer this one (the Wang one has more bugs). So i have some questions about your version: i installed it on my LineageOS 16.0 but there are some problems. I installed your app some month ago on my smartphone. Since the beginning there was a problem with the Announcement strip - the strip did not reveal after the restart of the phone (the only way to run it is do it manually via switch off and switch on the "Pernament annoucement" in the "Announcement" settings and Go back) and the 'Actual position' did not work too. 

**BUT after some time the version 2.608-foss (and i did not change knowingly on my phone nothing) surprisingly started to work**, i mean those features: 
a) revealing the Announcement strip after the phone restart (run at startup)  
b) 'Actual position' 

**BUT i reinstalled this app by accident and now it does not work again...** 
I tried the "Help" tips, but nothing works. 
But your app worked on my phone! 

With newest version 2.610-foss the "Annoucenment strip" does not work completely, i can not reveal it even manually.. (the procedure mention above does not work).

Can you help, please?

**Comment by mbestavros** [comment]
I just enabled the persistent notification (which is what I think you mean when you say "announcement strip") and it showed up perfectly fine after a reboot (I'm on a Pixel 4a 5G). In fact, it did so on the _upstream_ app as well. The behavior you're describing sounds very much like aggressive background activity restrictions -- though I realize you're on Lineage OS, so it's not likely something by your device's manufacturer. You could attempt to disable battery optimizations for Geometric Weather and see if that helps things.

Frankly, I'd respectfully encourage you to give the upstream app another try. There should be no functional differences between the two -- in fact, the upstream version has the advantage of half a year's worth of additional bug fixes and feature improvements, so I find it hard to believe the upstream version "has more bugs," as you say. If you do notice any, I'd encourage you to report them to the upstream repo (and I see you have reported this one there as well -- thank you!)

I cannot offer anything more beyond that. It's your right to use the forked app, but I've been **very** explicit that this fork is no longer supported; you should not expect further updates or bug fixes of any kind.
